trunk/bin/comparecatalogs.py
with a default to the previous version if no variable exists to make the script more flexible. This should be transparent to LCO
=> making path to pipeline git repository an environment variable 

trunk/src/lsc/myloopdef.py
When get_list is called, it eventually searched for objects ```LIKE _name.lower().replace('at20', 'at20%').replace('sn20', 'sn20%').replace(' ', '%')```. However, when get_standards is called and tries to match standards with object observations, it uses ```=name``` where name is exactly as specified by the user. This leads to the object being found by get_list but no standards found, making this issue hard to diagnose. This change replaces the definition of name in get_standards with the more flexible definition used by get_list.
=> Fix targname get standards

trunk/bin/calibratemag.py
calibratemag silently failed when no standards were found. This adds an error message. Its not clear to me which branch this should go on, I'm putting it on the export pipe branch since presumable LCO doesn't encounter this issue since standards are automatically ingested.
=> Fix calibratemag no stds

trunk/bin/LCOGTingest.py
The GSP uses ingestall.py to ingest its data on a cronjob. Data can also be ingested semi-manually with LCOGTingest.py, but then they are only added to photlcoraw and not photlco. This aligns both ingestion scripts to ingest into both tables.
Note, however, that outside users cannot use LCOGTingest.py to get proprietary data without credentials for archive.lco.global, but they can, for example, ingest standard star images this way.
=> also add images to photlco when ingesting with LCOGTingest.py

trunk/bin/calibratemag.py
The current version, does not mask columns correctly. When these columns have not been populated (likely you are creating the local sequence catalog for the first time), then these columns are empty (which is equivalent to being masked). However, if you create the catalog after completing the calibration of the SN using the local sequence, the nights without coincident standard star observations will be included in calculating the local sequence. Attached are figures of what the interactive plots look like before and after the fix (before has many more observations on it).
Before:
After:
=> Fix calibratemag to mask observations without standards

trunk/bin/lscmaketempl.py, trunk/src/lsc/myloopdef.py
This PR changes many `iraf.set(stdimage='imt1024')` -->` iraf.set(stdimage='imt2048')` and changes an imexamine call to explicitly specify z1 and z2 and removes the frame specification. @svalenti can elaborate on why this change was made.
=> Improve iraf image handling

trunk/src/lsc/mysqldef.py
Ingesting data from SN 2019qyl, we found some files were compress with Fpack (.fz) files while others were gzipped (.gz). Ingesttar.py was failing for some of the SNEx packages because they contained .fz files. This fix allows both file types to be ingested.
ingesttar.py -f snexdata_2020-08-20_22_39_23.853297_320_5971.tar.gz
=> adding the ability to ingest .fits.fz files 

trunk/bin/format_snex2.py
Quick script to reformat output of `-s getmag` into a snex2-friendly format, to make uploading external photometry easier. 
Tested on photometry files (both with all the 9999's and without them) and uploaded successfully to snex2.
=> Adding script to reformat photometry files so they can be uploaded to snex2

trunk/src/lsc/myloopdef.py, trunk/src/lsc/mysqldef.py
When creating a local sequence, if the sn or at is not put in front of the supernova name, then no standards are found. This PR pre-pends a % to whatever name the user provides
In the master branch, the following should return no standards
```
lscloop.py -n 2020cxd -e 20200201-20200331 --standard all -f U -s local -i --catalog $LCOSNDIR/standard/cat/apass/SN2020cxd_apass.cat --field landolt
```
In this branch it should return standards
=> adding % to the front of the sn name

trunk/bin/ingestall.py
Guider images from the OGG_calib and COJ_calib proposals are currently being downloaded (although they are not ingested into the database). This PR should avoid finding them at all by specifying that only images from the spectrographs (en05, en06, en12) should be downloaded and ingested.
=> avoid downloading guider images

trunk/bin/lscdiff.py
This is an intermittent error that I've encountered that is often fixed by running the image another time. I have not been able to identify what is causing it to occur, but the error is not properly caught so the processing of other images can continue. This change wraps the masking of data in an if statement to skip rather than throw an error and skips the image (after printing a warning) when it encounters the issue
=> Skip cases where mask and image are different sizes

Dockerfile, manual.md, trunk/bin/lscdiff.py, trunk/bin/lscloop.py, trunk/setup.py, trunk/src/lsc/myloopdef.py
@arcavi and I have both reported problems with `iraf.immatch.gregister` not aligning images correctly prior to subtraction. This might be due to temporary files...I haven't looked into it. However it was fairly easy to replace gregister with the pure-Python `reproject.reproject_interp` function associated with Astropy. This avoids the step of having to calculate the transformation, save it in a temporary file (`tmpcoo`), and then apply it to the images. I attached this to the existing `--no_iraf` option (although IRAF is still used for `fixpix`).
Possible downsides:
- adds a new dependency (`reproject`), but it's pip/conda installable
- `--show` no longer works to show the image alignment in real time, but I'm not sure if anyone used this anyway
=> Add option to use reproject instead of gregister for image alignment

supernova.sql, trunk/bin/comparecatalogs.py, trunk/bin/lscloop.py, trunk/bin/lscpsf.py, trunk/src/lsc/lscabsphotdef.py, trunk/src/lsc/sites.py, trunk/src/lsc/util.py
This PR:
1. Adds a column for gaia catalogs to the targets table of the db.
2. Changes `compare_catalogs.py` so that column gets populated.
3. Makes gaia catalogs the default selection for the psf stage, to alleviate problems with apass/sloan catalogs selecting galaxies.
This could use further testing, especially `compare_catalogs.py` -- I was having difficulty forcing re-ingestion of catalogs when I was tweaking values in that script, so making sure that it's properly functioning would be good. I also only tested the psf stage on the two targets that I had already ingested into my db (20hvf and 19yvq), and they're both pretty similar objects in medium density stellar fields offset from  an angularly small host. I'll ingest data from some more varied targets to make sure the catalogs work …
=> Add gaia catalogs for psf stage

trunk/src/lsc/myloopdef.py
This change occurs during the interactive `getmag` stage when inspecting details of an individual photometry point produced by difference imaging.
Tested on Dark with the following command, then clicking on an individual photometry point:
```
lscloop.py -n "2017gaw" -e 20170813-20200701 --filetype 3 -s getmag --difftype 0  --show --type mag -f g
```
but this can be tested on any supernova with difference imaging
=> changing display of difference image from percentile to zscale

trunk/bin/format_snex2.py, trunk/bin/lscloop.py, trunk/src/lsc/myloopdef.py
This PR allows users to upload their reduced photometry to SNEx2. Uploading can be done using the `--uploadtosnex2` flag in the `-s getmag` stage like this: 
`lscloop.py -n sn2019ein -e 20190501 -s getmag --type mag -o sn2019ein.dat --uploadtosnex2`
This flag takes the output file written during this stage (in this case, `sn2019ein.dat`), formats it in a SNEx2-readable format, and uploads it to SNEx2. It checks whether the selected photometry is background subtracted or not, and if so what subtraction algorithm was used. It also asks the user for additional input, including what group the user belongs to (i.e. LCO, UC Davis, etc.), if this is the final version of the data, if this data is used in any papers, and for the user's SNEx2 username and password.
As part of this PR, I changed the …
=> Upload photometry to snex2

trunk/bin/lscdiff.py, trunk/bin/lscloop.py, trunk/src/lsc/myloopdef.py
When PyZOGY was run on some images with a lot of sources, the default number of active pixel sources (science.size//20) allowed by sep was exceeded with the error:
> Exception: internal pixel buffer full: The limit of 838860 active object pixels over the detection threshold was reached. Check that the image is background subtracted and the detection threshold is not too low. If you need to increase the limit, use set_extract_pixstack.
This PR adds the flag --pixstack-limit so that the user can manually push this limit higher. 
This PR was tested by first running images without the --pixstack flag to demonstrate that the error was still produced then running with the flag, setting the --pixstack-limit to the image size (an upper limit) and showing that the image processed all the way …
=> adding --pixstack_limit flag

trunk/src/lsc/mysqldef.py
This fixes a problem discovered by Megan where targets wouldn't get created in the database correctly, which would prevent their images from getting ingested.
The traceback which started the investigation was:
```
supernova@5c8bd4b81c72:/Users/megannewsome/sirah/data$ LCOGTingest.py -S elp -T 1m0a -f U -s 2020-03-10 -e 2020-03-11 -r reduced -t STANDARD --public
Total number of frames: 2
Error 1054: Unknown column 'N' in 'field list'
```
I replicated this error on my installation and realized it was due to the incoming targets not having coordinates:
```
(Pdb) _targetid=lsc.mysqldef.gettargetid('',_ra,_dec,conn,.01,False)
Error 1054: Unknown column 'N' in 'field list'
*** SystemExit: 1
(Pdb) print _ra
N/A
(Pdb) print _dec
N/A
```
The `CAT-RA` header keyword was `N/A`. I am not totally sure …
=> Making sure newly ingested targets have correct RA/dec

trunk/src/lsc/lscpsfdef.py
Previously, when something went wrong in the PSF stage, the aperture correction would not be set and calibration would end with the error:
```
UnboundLocalError: local variable 'aperture_correction' referenced before assignment
```
which was misleading as this was a secondary error. This fix allows the code to correctly exit
One way to produce an error in the psf stage is to run it with `--show` but not have ds9 open.
```
lscloop.py -n L107 -e 20210223 -f V -t elp -s psf --show -F
```
This should produce the above error in the current pipeline after an error about IRAF task display.
On this branch it will only produce the error about IRAF task display.
One minor annoyance is that it still asks you if the PSF is good, but then marks it as bad since the stage didn't complete - but I think …
=> allowing psf stage to exit gracefully when it encounters an error

README.md
Summary of the edits - 
1. `xhost +local:docker` is sufficient (in linux at least), no need to allow X-connections from all sources which potentially might be insecure. Up to the reviewer.
2. In linux systems the previously existing docker command more than often fails to output a display connection. So, the additional arguments to the `docker run` command should hopefully resolve this issue.
3. I've also added a suggestion to modify the docker-compose.yml file and add these additional arguments, for ease of use. (I've got my instance of pipeline working this way after some research; I found a similar solution by *Lingzhi Wang* in the slack channel discussions afterwards)
4. Added a suggestion to open a ds9 windows after running the pipeline for the first time, to see if display output is …
=> Update Installation instructions for linux users

trunk/src/lsc/lscabsphotdef.py
The pipeline chooses which color term to calculate (e.g., B with B-V) based on what other images were taken on the same night at the same site. However it currently uses all images, including ones that are marked as bad. This means it won't be able to calculate a magnitude at the end because it needs a magnitude from those bad images. This fixes the query to select only images with `quality=127` (good).
=> ignore bad images when choosing color term filter

trunk/src/lsc/myloopdef.py
This mostly fixes the PSF display for very non-Gaussian PSFs, as brought up in [issue 95](https://github.com/LCOGT/lcogtsnpipe/issues/95). Tested with the extreme case there and also some more normal-looking PSFs (the first ones from 17eaw) to confirm it didn't break their display.
As stated in my response to the issue, this normalization is clearly not exactly correct, but I couldn't find where it was defined in the iraf code and this was the closest I could get. For very non-Gaussian PSFs it prints a warning to acknowledge that the display with `--no_iraf` might be inaccurate.
=> Updating normalization for --no_iraf PSF display

trunk/bin/ingestall.py
The pipeline was ingesting experimental frames that somehow got added as standard star observations to the archive. This PR will ignore those frames and only ingest frames which have `obstype='standard'` for photometric standards.
=> Only ingesting standard frames for photometric standards

manual.md
I've added some more suggestions for what to do when psf stage is failing (due to maxapercorr error). The instructions are found at two places in the manual, so for now I've added to both places. It might be better to combine both these.
=> Updated instruction for dealing with bad `-s psf` stage

trunk/src/lsc/lscabsphotdef.py
Fixed MuSCAT3 color terms. I used all our Muscat data from January 1st 2022 (arbitrary date), and calibrated them with PanSTARRS. These color terms could definitely be improved and done more thoroughly, but unless people start doing cosmology with Muscat data, these should be just fine for our everyday use. And most importantly, these are much closer to be correct than the random values the pipeline is currently using.
Moreover, the code now raises an Exception if a proper color term cannot be associated with the instrument. Before it just assigned random color terms. This way we can better control issues with new instruments in the future.
=> Fixed MuSCAT3 color terms

trunk/bin/lscpsf.py
This adds an option to adjust the datamax value, instead of the FWHM, when running the PSF stage with `--show`. I'm happy to change the message if you think it could be clearer. I was just trying to keep it relatively short.
=> Adjust datamax in interactive PSF stage

Dockerfile, manual.md, trunk/bin/lscloop.py, trunk/src/lsc/externaldata.py, trunk/src/lsc/lscabsphotdef.py, trunk/src/lsc/lscastrodef.py, trunk/src/lsc/mysqldef.py, trunk/src/lsc/util.py
This PR was modeled off of PR #80 which implemented MuSCAT
Other changes:
- This also slightly changes the way the color correction is used when no instrument is found. Previously there were site colors defined. I have removed them and now it defaults to 0 color correction and prints a warning to the screen that the color correction is 0 and suggests using the --unfix option to calculate a color correction.
- Fixed a bug in the wcs calculation (only used when BANZAI fails) for the fwhmgess3 for the sinistro telescopes
Testing:
I tested this on the 2024-02-06 data from proposal LCOEPO2014B-010 of SN 2024bch
I ran the following commands:
```
lscloop.py -n 2024bch -e 20240206 -T sq -s psf
lscloop.py -n 2024bch -e 20240206 -T sq -s psfmag
lscloop.py -n 2024bch -e 20240206 -T sq -s zcat #This …
```
=> Allow pipeline to process QHY600 CMOS detectors

trunk/bin/calibratemag.py, trunk/src/lsc/lscabsphotdef.py
I tested this by running `compare_catalogs.py` on dark and it properly downloaded Gaia catalogs.
I then ran the following to fully calibrate the data:
```
lscloop.py -n 'WISEAJ075041.08-302027.1' -s psf
lscloop.py -n 'WISEAJ075041.08-302027.1' -s psfmag
lscloop.py -n 'WISEAJ075041.08-302027.1' -s zcat
lscloop.py -n 'WISEAJ075041.08-302027.1' -s mag
```
This resulted in calibrated r and I band filter - z band doesn't have a zero point from the apass catalog - so this will not get an apparent magnitude
=> changing source_id to SOURCE_ID to match change in Gaia catalog output

Dockerfile
Some versions of mac os would crash trying to build the dockerfile in the ds9 from source. Building the packaged version of openssl does would crash if built using a standard make command. If you instead build the engines (which builds crypto first), the error goes away. I've built this with both the mac m1 default platform (arm64) and --platform=linux/x86_64 successfully on my mac that was having the issue.
=> Updates to fix ds9 build

trunk/bin/LCOGTingest.py
This allows people with an API key to use that to access the archive instead of entering the username and password on the command line. For example:
```
LCOGTingest.py -l 1 -s 2025-02-13 -P KEY2023B-002 -r reduced
```
should return no frames, whereas
```
export LCO_API_KEY=sdf087asdf987asdf0786987
LCOGTingest.py -l 1 -s 2025-02-13 -P KEY2023B-002 -r reduced
```
should return one frame.
You could also set this `LCO_API_KEY` environment variable in your `.bashrc` or similar.
If you have a portal account, you can get (or replace) your API key from https://observe.lco.global/accounts/profile.
=> add API token option to LCOGTingest.py

trunk/src/lsc/lscabsphotdef.py
There has been a strange crash in comparecatalogs.py. This was crashing in the SQL query to sdss. When I checked the response from the SDSS server it said "Uncaught error occurred" without more information. The bug was intermittent. If I used the exact parameters from AT 2024zkl, it would crash. If I changed the radius from 20.0 to 20 or 15.0 everything worked. Removing the newlines in the SQL query seemed to fix it in as much that it ran for 24zkl. Beyond that I haven't been able to reproduce the bug so its hard to validate it more than that.
=> Removed new lines in the sql query to sdss which was crashing intermittently
